from netmiko.linux import LinuxSSH
from datetime import datetime
from conf import Setting
import re

setting = Setting()

# Generated by IA
def remove_ansi_escape_sequences(text: str) -> str:
    """Remove ANSI escape sequences and terminal prompts from text"""
    # Remove all ANSI escape sequences and control characters
    ansi_escape = re.compile(r'(\x1B\[[0-9;]*[mGK]|\x1B\[[\?0-?]*[ -/]*[@-~]|\x1B[@-_]|[\x00-\x08\x0B\x0C\x0E-\x1F\x7F])')
    text = ansi_escape.sub('', text)
    
    # Remove leftover special characters that might be from incomplete ANSI sequences
    text = re.sub(r'[\[\?=>](?=\n|$)', '', text)
    
    # Remove terminal prompts (lines starting with >)
    lines = text.split('\n')
    lines = [line for line in lines if not line.strip().startswith('>')]
    text = '\n'.join(lines)
    
    # Remove lines that only contain special characters or whitespace
    lines = text.split('\n')
    lines = [line for line in lines if line.strip() and not re.match(r'^[\s=\[\?\->#]*$', line)]
    text = '\n'.join(lines)
    
    # Clean up extra whitespace at start and end, and multiple blank lines
    text = text.strip()
    text = re.sub(r'\n\n+', '\n', text)
    
    return text


def connect_to_nfware_server_via_ssh() -> LinuxSSH:
    try:
        ssh_connection = LinuxSSH(
            ip=setting.nfw_ip,
            port=setting.nfw_port,
            username=setting.nfw_user,
            password=setting.nfw_password
        )
        return ssh_connection
    except Exception as e:
        print(f"Error connecting to NFware server: {e}")
        return None


def get_config_from_nfware_server(ssh_connection: LinuxSSH) -> str:
    try:
        config = ssh_connection.send_command(setting.export_config_command)
        # Remove ANSI escape sequences from the config
        config = remove_ansi_escape_sequences(config)
        return config
    except Exception as e:
        print(f"Error fetching config from NFware server: {e}")
        return ""   


def save_backup_file_locally(config: str) -> dict:
    try:
        backup_file_name = f'backup_config__{datetime.now().strftime("%d-%m-%Y_%H-%M-%S")}.txt'
        backup_file_path = f'./backups/{backup_file_name}'
        with open(backup_file_path, "w") as backup_file:
            backup_file.write(config)
        return {"status": "success", "file_path": backup_file_path}
    except Exception as e:
        print(f"Error saving backup file locally: {e}")
        return {"status": "error", "message": str(e)}


def notify_backup_status(backup: dict) -> None:
    pass


def run() -> None:
    # Getting configs
    ssh_connection = connect_to_nfware_server_via_ssh()
    config = get_config_from_nfware_server(ssh_connection)
    ssh_connection.disconnect()

    if config == "":
        print("No config retrieved, aborting backup process.")
        return

    # Backup configs
    backup = save_backup_file_locally(config)

    # Notifying backup status in some channel (Telgram or e-mail) the status backup 
    notify_backup_status(backup)


if __name__ == "__main__":
    print('Starting backup process...')
    run()
