import re
import logging
import os
import argparse
from netmiko.linux import LinuxSSH
from datetime import datetime
from conf import Setting
from ftplib import FTP
from io import BytesIO

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("./logs/backup.log"),
        logging.StreamHandler()
    ]
)

setting = Setting()

def get_args():
    """
    Parse command-line arguments for backup mode selection.
    """
    parser = argparse.ArgumentParser(description="Backup NFware configuration script")

    parser.add_argument(
        "--mode",
        nargs="+",
        choices=["local", "samba_ftp"],
        required=True,
        help="Choose backup mode: 'local' to save on local disk, 'samba_ftp' to save on remote FTP server, or both."
    )

    return parser.parse_args()


# Generated by IA
def remove_ansi_escape_sequences(text: str) -> str:
    """
    Remove ANSI escape sequences and terminal prompts from text.
    
    Cleans the input text by removing all ANSI escape sequences, control characters,
    terminal prompts, and lines containing only special characters.
    
    Args:
        text (str): The text to clean.

    Returns:
        str: Cleaned text without ANSI sequences and artifacts.
    """
    # Remove all ANSI escape sequences and control characters
    ansi_escape = re.compile(r'(\x1B\[[0-9;]*[mGK]|\x1B\[[\?0-?]*[ -/]*[@-~]|\x1B[@-_]|[\x00-\x08\x0B\x0C\x0E-\x1F\x7F])')
    text = ansi_escape.sub('', text)
    
    # Remove leftover special characters that might be from incomplete ANSI sequences
    text = re.sub(r'[\[\?=>](?=\n|$)', '', text)
    
    # Remove terminal prompts (lines starting with >)
    lines = text.split('\n')
    lines = [line for line in lines if not line.strip().startswith('>')]
    text = '\n'.join(lines)
    
    # Remove lines that only contain special characters or whitespace
    lines = text.split('\n')
    lines = [line for line in lines if line.strip() and not re.match(r'^[\s=\[\?\->#]*$', line)]
    text = '\n'.join(lines)
    
    # Clean up extra whitespace at start and end, and multiple blank lines
    text = text.strip()
    text = re.sub(r'\n\n+', '\n', text)
    
    return text


def connect_to_nfware_server_via_ssh() -> LinuxSSH:
    """
    Establish SSH connection to NFware server.
    
    Connects to the NFware device using credentials from settings.
    
    Returns:
        LinuxSSH: Active SSH connection object or None if connection fails.
    """
    try:
        ssh_connection = LinuxSSH(
            ip=setting.nfw_ip,
            port=setting.nfw_port,
            username=setting.nfw_user,
            password=setting.nfw_password,
            timeout=10
        )
        return ssh_connection
    except Exception as e:
        logging.error(f"Error connecting to NFware server: {e}")
        return None


def connection_to_ftp_server() -> FTP:
    """
    Establish FTP connection to remote server.
    
    Connects to the FTP server using credentials from settings.
    
    Returns:
        FTP: Active FTP connection object or None if connection fails.
    """
    try:
        ftp = FTP(setting.ftp_host)
        ftp.login(user=setting.ftp_user, passwd=setting.ftp_password)
        return ftp

    except Exception as e:
        logging.error(f"Error connecting to FTP server: {e}")
        raise


def get_config_from_nfware_server(ssh_connection: LinuxSSH) -> str:
    """
    Retrieve and clean configuration from NFware server.
    
    Sends the export command to NFware and removes ANSI escape sequences
    and terminal artifacts from the output.
    
    Args:
        ssh_connection (LinuxSSH): Active SSH connection to NFware server.
        
    Returns:
        str: Clean configuration text or empty string if retrieval fails.
    """
    try:
        config = ssh_connection.send_command(setting.export_config_command)
        # Remove ANSI escape sequences from the config
        config = remove_ansi_escape_sequences(config)
        return config
    except Exception as e:
        logging.error(f"Error fetching config from NFware server: {e}")
        return ""   


def save_backup_file_locally(config: str) -> str:
    """
    Save configuration to a local backup file.
    
    Creates a timestamped backup file in the backups directory
    with the provided configuration content.
    
    Args:
        config (str): Configuration content to save.
        
    Returns:
        dict: Status dictionary with 'success' or 'error' status and file path or error message.
    """
    try:
        logging.info("Saving backup file locally...")

        # Ensure the backups directory exists
        os.makedirs("./backups", exist_ok=True)
        
        # Create a timestamped backup file name
        backup_file_name = f'backup_config__{datetime.now().strftime("%d-%m-%Y_%H-%M-%S")}.txt'
        backup_file_path = f'./backups/{backup_file_name}'
        with open(backup_file_path, "w") as backup_file:
            backup_file.write(config)
        return backup_file_path
    except Exception as e:
        logging.error(f"Error saving backup file locally: {e}")
        raise


def save_backup_file_on_samba_ftp_server(config: str) -> dict:
    """
    Save configuration to a remote Samba/FTP server.
    
    Creates a timestamped backup file on the remote server
    with the provided configuration content.
    
    Args:
        config (str): Configuration content to save.
        
    Returns:
        dict: Status dictionary with 'success' or 'error' status and file path or error message.
    """
    try:
        logging.info("Saving backup file on Samba/FTP server...")
        backup_file_name = f'backup_config__{datetime.now().strftime("%d-%m-%Y_%H-%M-%S")}.txt'

        # Connect to FTP server
        ftp_connection = connection_to_ftp_server()
        if not ftp_connection:
            raise Exception("Failed to connect to FTP server")
        
        ftp_connection.cwd('CGNAT/NFWARE01') 
        
        # Convert config string to file-like object
        file_obj = BytesIO(config.encode())
        
        # Upload file
        ftp_connection.storbinary(f"STOR {backup_file_name}", file_obj)

        ftp_connection.quit()

        
        # return {"status": "success", "file_path": backup_file_path}
    except Exception as e:
        logging.error(f"Error saving backup file on Samba/FTP server: {e}")
        return {"status": "error", "message": str(e)}


def notify_backup_status(backup: dict) -> None:
    pass


def run() -> None:
    """
    Execute the complete backup workflow.
    
    Orchestrates the entire backup process:
    1. Connects to NFware server via SSH
    2. Retrieves and cleans the configuration
    3. Saves backup file locally
    4. Sends status notification
    """
    args = get_args()

    # Getting configs
    ssh_connection = None
    try:
        ssh_connection = connect_to_nfware_server_via_ssh()
        
        if not ssh_connection:
            logging.warning("SSH connection failed, aborting backup process.")
            return

        config = get_config_from_nfware_server(ssh_connection)

        if not config:
            logging.warning("No config retrieved, aborting backup process.")
            return

    except Exception as e:
        logging.error(f"Unexpected error during getting configs to backup: {e}")
        return
    finally:
        if ssh_connection:
            ssh_connection.disconnect()

    # Saving Backup configs
    try:
        if "local" in args.mode:
            save_backup_file_locally(config)
        if "samba_ftp" in args.mode:
            save_backup_file_on_samba_ftp_server(config)

        return
    except Exception as e:
        logging.error(f"Unexpected error during saving backup file: {e}")
        return


if __name__ == "__main__":
    logging.info('Starting backup process...')
    run()


# Add a function to save file remotly to a FTP server or google drive -- OK
# Implementing logging instead of print statements would provide better traceability and debugging capabilities. -- OK
# Add a function to send notifications (e.g., via email or Telegram) to inform about the backup status, including success or failure details.
# Standardizing the raise of exceptions and error handling across all functions would improve the robustness of the code
